- name: Copy elasticsearch.yml to each node
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0640'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch service is enabled and started
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
