- name: Copy Elasticsearch configuration file
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: ansible
    group: elasticsearch
    mode: '0660'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch service is started and enabled
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
