- name: Create ansible user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    state: present

- name: Add ansible user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible
    line: "ansible ALL=(ALL) NOPASSWD:ALL"
    create: yes
    mode: '0440'
    validate: 'visudo -cf %s'

- name: Deploy SSH public key for ansible user
  ansible.builtin.authorized_key:
    user: ansible
    key: "{{ lookup('file', '~/.ssh/ansible_key.pub') }}"
    state: present
