- name: Ensure Jenkins is stopped before modifying config
  ansible.builtin.service:
    name: jenkins
    state: stopped
  become: yes

- name: Copy Jenkins config.xml with user details
  ansible.builtin.template:
    src: config.xml.j2
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
    mode: '0644'
    backup: yes
  become: yes
  notify: Restart Jenkins

- name: Ensure Jenkins is started after config update
  ansible.builtin.service:
    name: jenkins
    state: started
  become: yes

- name: Wait for Jenkins to be fully up
  ansible.builtin.wait_for:
    port: 8080
    state: started
    timeout: 60
