- name: Stop MongoDB service
  ansible.builtin.service:
    name: mongod
    state: stopped
  ignore_errors: yes  # Continue even if the service is already stopped

- name: Uninstall MongoDB packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools

- name: Remove MongoDB repository file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/mongodb-org-8.0.list
    state: absent

- name: Remove MongoDB GPG keyring
  ansible.builtin.file:
    path: /usr/share/keyrings/mongodb-server-8.0.gpg
    state: absent

- name: Delete MongoDB data directory
  ansible.builtin.file:
    path: /var/lib/mongodb
    state: absent

- name: Delete MongoDB log directory
  ansible.builtin.file:
    path: /var/log/mongodb
    state: absent

- name: Delete MongoDB configuration files
  ansible.builtin.file:
    path: /etc/mongod.conf
    state: absent

- name: Update apt cache after removal
  ansible.builtin.apt:
    update_cache: yes
