- name: Import Elasticsearch GPG key
  ansible.builtin.shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elastic-8.x

- name: Update apt cache and install Elasticsearch
  ansible.builtin.apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Start Elasticsearch service
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
